version: "2"
linters:
  enable:
    - unconvert
  settings:
    errcheck:
      check-blank: true
    govet:
      disable:
        - fieldalignment
      enable-all: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
        path: _test\.go
      - linters:
          - govet
        text: shadow
      - linters:
          - errcheck
        text: tx\.Rollback
      - linters:
          - errcheck
        text: config\.Path
      - linters:
          - errcheck
        text: strconv\.
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
